FROM ubuntu:18.04
MAINTAINER pbrian
LABEL Name="pbriandev" Version=0.0.1

### Constants
ENV WKDIR /staging
ENV USERHOME /home/pbrian

{{ apt }}

{{ py3 }}

{{ sshX }}

{{ latex }}

{{ user }}

{{ baseconfig }}



EXPOSE 22
ENTRYPOINT ["/home/pbrian/ENTRYPOINT.sh"]


